#!/usr/bin/env python3
"""Rasterizes Pillow's bundled Aileron font (CC0 / public domain) into
common/rd_font_data.h: antialiased 8-bit alpha glyphs for ASCII 32..126 at
every pixel size the UI draws (for 1x and 2x displays), so text is always
drawn 1:1 and never scaled (scaling glyphs is what makes text look soft).
The alpha atlases are compressed with TetherDesk's LZ format (rd_codec.c).
Build-time tool only; the generated header is checked in."""
import os
from PIL import Image, ImageDraw, ImageFont

SIZES = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 34, 35, 36,
         38, 40, 41, 42, 45, 48, 52, 56]
FIRST, LAST = 32, 126
out_path = os.path.join(os.path.dirname(__file__), "..", "common", "rd_font_data.h")


def lz_compress(src: bytes) -> bytes:
    """Greedy LZ77 in the LZ4-block layout that rd_lz_decompress() reads."""
    out = bytearray()
    n = len(src)
    table = {}
    anchor = ip = 0

    def put_len(v):
        while v >= 255:
            out.append(255)
            v -= 255
        out.append(v)

    def emit(lit_end, off=None, ml=0):
        lit = lit_end - anchor
        token = (min(lit, 15) << 4) | (min(ml - 4, 15) if off else 0)
        out.append(token)
        if lit >= 15:
            put_len(lit - 15)
        out.extend(src[anchor:lit_end])
        if off:
            out.extend((off & 255, off >> 8))
            if ml - 4 >= 15:
                put_len(ml - 4 - 15)

    limit = n - 12
    while ip <= limit:
        key = src[ip:ip + 4]
        cand = table.get(key)
        table[key] = ip
        if cand is not None and ip - cand <= 65535:
            ml = 4
            maxm = n - 5 - ip
            while ml < maxm and src[cand + ml] == src[ip + ml]:
                ml += 1
            emit(ip, ip - cand, ml)
            ip += ml
            anchor = ip
        else:
            ip += 1
    emit(n)  # final literal-only sequence
    return bytes(out)


lines = [
    "/* Generated by tools/gen_font.py from Aileron Regular (CC0). Do not edit. */",
    "#ifndef RD_FONT_DATA_H",
    "#define RD_FONT_DATA_H",
    "/* Include only from rd_font.c; use the rd_font.h API elsewhere. */",
    "#include \"rd_font.h\"",
    "",
]
faces = []
total_raw = total_lz = 0
for size in SIZES:
    font = ImageFont.load_default(size=size)
    ascent, descent = font.getmetrics()
    height = ascent + descent + 1
    glyphs, x = [], 0
    for c in range(FIRST, LAST + 1):
        ch = chr(c)
        l, _, r, _ = font.getbbox(ch)
        adv = round(font.getlength(ch))
        w = max(r, adv, 1) - min(l, 0) + 1
        glyphs.append((ch, x, w, adv, min(l, 0)))
        x += w
    atlas = Image.new("L", (x, height), 0)
    d = ImageDraw.Draw(atlas)
    for ch, gx, w, adv, left in glyphs:
        d.text((gx - left, 0), ch, font=font, fill=255)
    raw = atlas.tobytes()
    lz = lz_compress(raw)
    total_raw += len(raw)
    total_lz += len(lz)
    name = f"rd_font_{size}"
    lines.append(f"static const rd_glyph {name}_glyphs[{len(glyphs)}] = {{")
    lines.append("    " + ", ".join(f"{{{gx},{w},{adv}}}" for _, gx, w, adv, _ in glyphs))
    lines.append("};")
    lines.append(f"static const uint8_t {name}_lz[{len(lz)}] = {{")
    for i in range(0, len(lz), 40):
        lines.append("    " + ",".join(str(v) for v in lz[i:i + 40]) + ",")
    lines.append("};")
    faces.append(f"{{{size}, {ascent}, {height}, {x}, {name}_glyphs, {name}_lz, {len(lz)}}}")
lines += [
    "",
    f"#define RD_FONT_FACE_COUNT {len(faces)}",
    f"static const rd_font_face rd_font_faces[RD_FONT_FACE_COUNT] = {{",
    "    " + ",\n    ".join(faces),
    "};",
    "#endif",
    "",
]
with open(out_path, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {os.path.normpath(out_path)}: {len(SIZES)} sizes, {total_raw // 1024} KiB of glyphs -> "
      f"{total_lz // 1024} KiB compressed")
