#!/usr/bin/env python3
"""Rasterizes Pillow's bundled Aileron font (CC0 / public domain) into
common/rd_font_data.h: antialiased 8-bit alpha glyphs for ASCII 32..126 at
two pixel sizes (1x and 2x displays). Build-time tool only; the generated
header is checked in so building TetherDesk never needs Python."""
import os
from PIL import Image, ImageDraw, ImageFont

SIZES = [14, 28]
FIRST, LAST = 32, 126
out_path = os.path.join(os.path.dirname(__file__), "..", "common", "rd_font_data.h")

lines = [
    "/* Generated by tools/gen_font.py from Aileron Regular (CC0). Do not edit. */",
    "#ifndef RD_FONT_DATA_H",
    "#define RD_FONT_DATA_H",
    "#include <stdint.h>",
    "",
    "typedef struct rd_glyph { uint16_t x, w, advance; } rd_glyph;",
    "typedef struct rd_font_face {",
    "    int size, ascent, height, atlas_w;",
    "    const rd_glyph *glyphs; /* ASCII 32..126 */",
    "    const uint8_t *alpha;   /* atlas_w x height, row-major */",
    "} rd_font_face;",
    "",
]
faces = []
for size in SIZES:
    font = ImageFont.load_default(size=size)
    ascent, descent = font.getmetrics()
    height = ascent + descent + 1
    glyphs, x = [], 0
    for c in range(FIRST, LAST + 1):
        ch = chr(c)
        l, _, r, _ = font.getbbox(ch)
        adv = round(font.getlength(ch))
        w = max(r, adv, 1) - min(l, 0) + 1
        glyphs.append((ch, x, w, adv, min(l, 0)))
        x += w
    atlas = Image.new("L", (x, height), 0)
    d = ImageDraw.Draw(atlas)
    for ch, gx, w, adv, left in glyphs:
        d.text((gx - left, 0), ch, font=font, fill=255)
    px = atlas.load()
    name = f"rd_font_{size}"
    lines.append(f"static const rd_glyph {name}_glyphs[{len(glyphs)}] = {{")
    lines.append("    " + ", ".join(f"{{{gx},{w},{adv}}}" for _, gx, w, adv, _ in glyphs))
    lines.append("};")
    data = [px[i % x, i // x] for i in range(x * height)]
    lines.append(f"static const uint8_t {name}_alpha[{len(data)}] = {{")
    for i in range(0, len(data), 32):
        lines.append("    " + ",".join(str(v) for v in data[i:i + 32]) + ",")
    lines.append("};")
    faces.append(f"{{{size}, {ascent}, {height}, {x}, {name}_glyphs, {name}_alpha}}")
lines += [
    "",
    f"static const rd_font_face rd_font_faces[{len(faces)}] = {{",
    "    " + ",\n    ".join(faces),
    "};",
    "#endif",
    "",
]
with open(out_path, "w") as f:
    f.write("\n".join(lines))
print("wrote", os.path.normpath(out_path))
